### ISSUE TITLE
1.14.4 double slab issue upon removing 1.4.0

### ISSUE THREAD

**Issue by warcommando2** [CJMinecraft01/DoubleSlabs#46] opened 2020-06-05 18:40 UTC
had a issue lastnight with update DoubleSlabs-1.14-1.4.0, went to remove the slab and it would crash me every time i go to remove it, not sure if it was due to me being in creative mode or not

pastebin link:
https://pastebin.com/sJBQifbK

**Comment by CJMinecraft01** [comment] 2020-06-06 08:58
Duplicate of #47

**Closed as completed by CJMinecraft01** 2020-06-06 08:58 UTC
