### ISSUE TITLE
Crash when I try to break a verticle slab

### ISSUE THREAD

**Issue by babydabblemlp** [CJMinecraft01/DoubleSlabs#155] opened 2020-11-05 20:37 UTC
Here is the crash report. I cannot get into this game anymore. As soon as it loads it crashes.

[crash-2020-11-05_13.32.00-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5497292/crash-2020-11-05_13.32.00-server.txt)

**Comment by Charmanth** [comment] 2020-12-05 21:23
This happened to me as well on my server.  Forge 35.1.7, mod file version 3.4.10.

**Comment by BigPingo2** [comment] 2020-12-08 02:39
Same here. I also have to use 0.1.0.0 because 0.1.1.0 crashes my server on startup.

**Comment by TheidenHD** [comment] 2020-12-17 15:50
https://github.com/TheidenHD/DoubleSlabs/releases/tag/0.11.1

**Comment by CJMinecraft01** [comment] 2020-12-24 22:34
Thank you for the bug report and sorry for the delayed response. I believe this is a duplicate of #140, so sorry for the delay :)

**Closed as completed by CJMinecraft01** 2020-12-24 22:34 UTC
Labels: bug, duplicate, 1.12.x
