### ISSUE TITLE
Minecraft just keeps asking for more RAM.

### ISSUE THREAD

**Issue by HauntedSniper** [CJMinecraft01/DoubleSlabs#139] opened 2020-10-02 13:31 UTC
**So, here's the thing. I was making a mansion and everything was neat, but then I wanted to duplicate the mansion with WorldEdit and it crashed the game (well froze and then I had to close the game). 
That was weird since I had copied a bigger pyramid before and nothing happened then, I then tried to copy and paste with Building Gadgets, and it did paste, but the game kept freezing every second.

 I had to close the game since it didn't crash, and I had to add more RAM, I have plenty, so it wasn't a problem to allocate more, but it was strange. But as I kept adding more RAM, and entering the game, Task Manager showed me that Minecraft kept maxing on RAM every time, and the freezing didn't stop. Until I got to 12 RAM, the game just froze and crashed by itself, giving me this crash report showing me that this mod had something to do with the problem, not sure what it may be.**

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/2/20 8:10 AM
Description: Playing level event

java.lang.NullPointerException: Playing level event
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock.lambda$getSoundType$19(DoubleSlabBlock.java:324) ~[?:2.11.5] {re:classloading}
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock$$Lambda$17878/231091588.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock.getSoundType(DoubleSlabBlock.java:324) ~[?:2.11.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.getSoundType(IForgeBlockState.java:650) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:1100) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_180439_a(WorldRenderer.java:3665) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinWorldRenderer,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:834) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.block.Block.func_176208_a(Block.java:720) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.func_176208_a(DynamicSlabBlock.java:225) ~[?:2.11.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:217) ~[?:?] {re:classloading,re:mixin}
	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.removedByPlayer(DynamicSlabBlock.java:218) ~[?:2.11.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:167) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_178891_a(PlayerController.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:133) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_180511_b(PlayerControllerOF.java:51) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1226) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1538) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1074993056.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path, and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock.lambda$getSoundType$19(DoubleSlabBlock.java:324)
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock$$Lambda$17878/231091588.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at cjminecraft.doubleslabs.common.blocks.DoubleSlabBlock.getSoundType(DoubleSlabBlock.java:324)
	at net.minecraftforge.common.extensions.IForgeBlockState.getSoundType(IForgeBlockState.java:650)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:1100)
	at net.minecraft.client.renderer.WorldRenderer.func_180439_a(WorldRenderer.java:3665)

-- Level event being played --
Details:
	Block coordinates: World: (272,10,-19), Chunk: (at 0,0,13 in 17,-2; contains blocks 272,0,-32 to 287,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Event source: ClientPlayerEntity['RipHSniper'/72, l='MpServer', x=271.84, y=11.00, z=-21.43]
	Event type: 2001
	Event data: 147634
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:834)
	at net.minecraft.block.Block.func_176208_a(Block.java:720)
	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.func_176208_a(DynamicSlabBlock.java:225)
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:217)
	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.removedByPlayer(DynamicSlabBlock.java:218)
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:167)
	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:111)
	at net.minecraft.client.multiplayer.PlayerController.func_178891_a(PlayerController.java:76)
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:133)
	at net.optifine.override.PlayerControllerOF.func_180511_b(PlayerControllerOF.java:51)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1226)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1538)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['RipHSniper'/72, l='MpServer', x=271.84, y=11.00, z=-21.43]]
	Chunk stats: Client Chunk Cache: 441, 272
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 2042461880191278340
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (224,4,16), Chunk: (at 0,0,0 in 14,1; contains blocks 224,0,16 to 239,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 518069 game time, 50969 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1074993056.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4361932520 bytes (4159 MB) / 12851347456 bytes (12256 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		vanillaextension-1.15.2-1.0.3.jar Vanilla Extension {vanillaextension@1.15.2-1.0.3 DONE}
		roughmobsrevamped-1.15.2-4.1.2.jar Rough Mobs Revamped {roughmobsrevamped@version DONE}
		ElenaiDodge-1.15.2-1.7.0.jar Elenai Dodge {elenaidodge@1.15.2-1.7.0 DONE}
		DoggyTalents-1.15.2-1.15.2.3 (1).jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 DONE}
		flower-breeding-1.15.2-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
		deadlyendphantoms-1.15.2-1.01.jar Deadly End Phantoms {deadlyendphantoms@1.01 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.0.15.jar TerraForged {terraforged@0.0.15 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		Apotheosis-1.15.2-3.3.5.jar Apotheosis {apotheosis@3.3.5 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2 (1).jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2 (1).jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		SnowRealMagic-1.15.2-1.7.5 (1).jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		shetiphiancore-1.15-3.7.2.jar ShetiPhian-Core {shetiphiancore@3.7.2 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		corpse-1.15.2-1.0.6.jar Corpse {corpse@1.15.2-1.0.6 DONE}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		GentleFawn-1.1.1-MC1.15.2.jar Gentle Fawn {gentlefawn@1.1.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		BetterDrowning-1.15.2-1.0.3.jar BetterDrowning {betterdrowning@1.0.3 DONE}
		masonry-1.15.2-0.3.4 (1).jar Masonry {masonry@NONE DONE}
		simplefarming-1.15.2-1.3.0.jar Simple Farming {simplefarming@1.15.1-1.3.0 DONE}
		xercamod-1.15.2-2.6.jar Xerca Mod {xercamod@1.15.2-2.6 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		horse_colors-1.15.2-1.4.0.1.jar Realistic Horse Genetics {horse_colors@1.15.2-1.4.0.1 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		Mushroom+Quest_1.15.2_v2.3.jar Mushroom Quest {mushroomquest@1.0.0 DONE}
		EndReborn+[0.6.1].jar End: Reborn {endreborn@0.6.1 DONE}
		lottaterracotta-1.15.2-1.3.1.jar Lotta Terracotta {lottaterracotta@1.15.2-1.3.1 DONE}
		furniture-7.0.0-pre16-1.15.1 (1).jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		productivebees-1.15.2-0.3.2.jar Productive Bees {productivebees@1.15.2-0.3.2 DONE}
		+skeleton-expansion-3.0.1_1.15.2.jar Skeleton Expansion+ {skeleton_expansion@1.0.0 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		Craft_and_Hunt_V1.1.0_MC_1.15.2.jar Craft and Hunt {craftandhunt@0.9 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		Mexicraft+1.0.1.jar Mexicraft {mexicraft@1.0.1 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		OptiForge-MC1.15.2-0.1.27.jar OptiForge {optiforge@0.1.27 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		SneakyMagic-v2.0-1.15.2.jar Sneaky Magic {sneakymagic@2.0 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		WallpaperCraft-1.15.2-1.2.4.jar Wallpapercraft {wallpapercraft@1.2.4 DONE}
		WallpapercraftSlabs-1.15.2-1.1.0.jar Wallpapercraft - Slabs! {wallpapercraftslabs@1.1.0 DONE}
		WallpapercraftStairs-1.15.2-1.1.1.jar Wallpapercraft - Stairs {wallpapercraftstairs@1.1.1 DONE}
		EnameledArmor-1.15.1-1.0.0.5.jar Enameled Armor Mod {ea@1.0.0.5 DONE}
		sweetconcrete-1.15.2-1.7.1.jar Sweet Concrete {sweetconcrete@1.15.2-1.7.1 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		EnhancedVanilla_Snapshot_20w27a-Forge-1.15.2.31.2.0.jar Enhanced Vanilla {enhancedvanilla@Snapshot 20w27a DONE}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
		iceandfire-2.0.1.jar Ice and Fire {iceandfire@2.0.1 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		beyond_the_nether_wastes_v_1.1.0.jar Beyond The Nether Wastes {btnw@1.0.0 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		goprone-1.15.x-1.3.0.jar GoProne {goprone@1.15.x-1.3.0 DONE}
		Bones-1.15.2-1.3.2.jar Bones {bones@1.15.2-1.3.2 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.6.4b.jar CoFH Core {cofh_core@0.6.4b DONE}
		ensorcellation-1.15.2-0.6.0b.jar Ensorcellation {ensorcellation@0.6.0b DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		packedup-1.0.18-mc1.15.jar PackedUp {packedup@1.0.18 DONE}
		archers_paradox-1.15.2-0.6.0b.jar Archer's Paradox {archers_paradox@0.6.0b DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		polymorph-FORGE-1.15.2-0.9.jar Polymorph {polymorph@FORGE-1.15.2-0.9 DONE}
		multibeds-1.15-1.6.1.jar Multi-Beds {multibeds@1.6.1 DONE}
		AutoRegLib-1.5-40 (1).jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 DONE}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 DONE}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 DONE}
		DoubleSlabs-1.15-2.11.5.jar Double Slabs {doubleslabs@2.11.5 DONE}
		lanterncolors-1.15.2-1.0.1.jar Lantern Colors {lanterncolors@1.15.2-1.0.1 DONE}
		TaigaAdditions+[0.1.2].jar Taiga Additions {taigaexpansion@0.1.2 DONE}
		WorldEdit-CUI-FE3-1.15.2-3.0.5 (1).jar WorldEdit CUI Forge Edition 3 {worldeditcuife3@3.0.5 DONE}
		worldedit-forge-mc1.15.2-7.1.0 (1).jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		mobcatcher-2.2 (1).jar Mob Catcher {mobcatcher@2.2 DONE}
		ilikewood-1.15.2-2.2.2.0 (2).jar I Like Wood {ilikewood@1.15.2-2.2.2.0 DONE}
		Aquaculture-1.15.2-2.0.20.jar Aquaculture 2 {aquaculture@1.15.2-2.0.20 DONE}
		ExtendedNetherBackport-1.15.2-Beta-4.1.2.jar Extended Nether Backport {extendednether@4.1.2 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Launched Version: 1.15.2-forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/DoggyTalentsDogs (incompatible), file/Thorolhugil's Cute Squids (incompatible), file/Creatures+, file/Haston's Foxes, file/PupleDrago (incompatible), file/RSRecolor Green
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**One thing I failed to add, Building Gadgets doesn't seem to work well with this mod, marking double slabs as missing texture and not automatically placing a slab over another slab. But I feel like it's more a problem on the side.**

**Comment by Paspartout** [comment] 2020-11-14 18:53
We were having a similar problem. Using VisualVM I could determine cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_226984_a_ () using all the cpu. I suspect that being the tick function and somehow allocating a lot of memory.

Here is a screenshot of the trace:

![grafik](https://user-images.githubusercontent.com/2720369/99154814-f916fe80-26b2-11eb-9e43-9ad1ff2e4b69.png)

I hope this helps.

**Comment by Paspartout** [comment] 2020-11-20 14:19
I think this might be a duplicate of issue #137

**Comment by CJMinecraft01** [comment] 2020-12-24 22:08
The crash issue I believe is a duplicate of #138 and as @Paspartout has said, the RAM issue is a duplicate of #137. Please refer to those issues. Sorry for the delay in response

**Closed as completed by CJMinecraft01** 2020-12-24 22:08 UTC
Labels: bug, duplicate, 1.15.x
