### ISSUE TITLE
Mod maxes out memory

### ISSUE THREAD

**Issue by Gebroeders-S** [CJMinecraft01/DoubleSlabs#180] opened 2021-04-05 21:36 UTC
After a while of using this mod, it started using up my memory increasingly until I suffered severe lag spikes every 2 seconds or so. Is there a fix for this?

by the way, this happened while I allocated up to 10GB.

**Comment by CJMinecraft01** [comment] 2021-04-13 14:27
Duplicate of #166. Please refer to that issue :)

**Closed as completed by CJMinecraft01** 2021-04-13 14:27 UTC
