### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by agentwolf88** [CJMinecraft01/DoubleSlabs#109] opened 2020-08-24 19:53 UTC
https://paste.ee/p/mPtVL

**Comment by CJMinecraft01** [comment] 2020-09-17 09:01
Hi! Thanks for the bug report. From looking into this further, it appears that this issue is a duplicate of #119 and #107 so please follow the issue there. Whilst the issue occurred under a different scenario, it crashes on the same function so will be fixed at the same time :)

**Closed as completed by CJMinecraft01** 2020-09-17 09:01 UTC
Labels: bug, duplicate, 1.12.x
