### ISSUE TITLE
[1.14.4] when reloaded, double-slabs revert to a missing texture.

### ISSUE THREAD

**Issue by Alkiasan** [CJMinecraft01/DoubleSlabs#40] opened 2020-05-01 23:15 UTC
Hi, using v1.2.5 of DoubleSlabs with minecraft 1.14.4.
Whenever a double-slab is placed (In this case, a double stone bricks slab), the texture works normally, however, upon unloading and loading the chunks (Serverside, reloading the chunks clientside doesn't cause it), the texture changes into a missing texture.
![2020-05-02_00 08 34](https://user-images.githubusercontent.com/62717881/80847978-84461080-8c09-11ea-99c3-a116d1818f59.png)

Modlist: 
AquaCulture 2
AutoRegLib
BookShelf
CarryOn
Cooking For Blockheads
Cosmetic Armor Reworked
IBEEditor
JustEnoughResources
JustEnoughItems
Lighting Wand
MixinBootstrap
MorePlayerModels
Quark (The piston control has been disabled in quark's config. Noticed this was an issue for others using Quark alongside Doubleslabs)
WorldProtector
XLFoodMod
Backpacked
Crayfish's furniture
Cosmetic Beds
Discord Integration
Decorative Blocks
Extended Lights
Illuminations
Immersive Portals
Macaw's bridges + roofs
mGUI
NoPhantomNoCry
PHC2 Crops/Trees/Core
Sisser
SwingThroughGrass
Tetra
ThutPerms/Essentials
WorldEdit
UtilityWorlds
XercaMusic/Paint
Torch Slabs
Double Slabs
CraftTweaker

**Comment by Alkiasan** [comment] 2020-05-01 23:18
Update: removed my resource packs, and the texture changed to this.
![2020-05-02_00 17 11](https://user-images.githubusercontent.com/62717881/80848218-7644bf80-8c0a-11ea-940e-bbcaedf7ff98.png)
Really strange.
Cycles every time i change resourcepacks, probably just minecraft trying to fill in the gap lol

**Comment by Alkiasan** [comment] 2020-05-01 23:31
Update 2: Found this error clientside
![image](https://user-images.githubusercontent.com/62717881/80848760-4696b700-8c0c-11ea-8136-cbaf86cce72a.png)

**Comment by CJMinecraft01** [comment] 2020-05-15 15:52
I believe this is a duplicate of #15 and may be due to having Immersive Portals installed

**Closed as completed** 2020-06-03 03:40 UTC
Labels: duplicate
