### ISSUE TITLE
Crash while walking over vertically placed slab.

### ISSUE THREAD

**Issue by DavidosWolfe667** [CJMinecraft01/DoubleSlabs#73] opened 2020-06-25 22:11 UTC
Playing on Engineer's Life, got sick of not being able to combine slabs.

Seems to be triggered after walking over vertical planks.

See attached log.
[crash-2020-06-26_00.09.12-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4834067/crash-2020-06-26_00.09.12-client.txt)
[crash-2020-06-26_00.05.54-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4834068/crash-2020-06-26_00.05.54-client.txt)

**Comment by DavidosWolfe667** [comment] 2020-06-25 22:38
Seems a very specific doorway only, any other passage way works, I don't get it.

**Comment by CJMinecraft01** [comment] 2020-06-26 10:47
This is a duplicate of #70

**Closed as completed** 2020-06-26 11:28 UTC
Labels: bug, duplicate, 1.15.x, 1.14.x, 1.12.x
