### ISSUE TITLE
Vertical slabs are invisible with Optifine installed

### ISSUE THREAD

**Issue by agentwolf88** [CJMinecraft01/DoubleSlabs#52] opened 2020-06-08 18:10 UTC
When i place a slab with shift, the slab is invisible.

**Comment by CJMinecraft01** [comment] 2020-06-08 21:36
Which slab was you trying to place and can you show me the log please?

**Comment by agentwolf88** [comment] 2020-06-09 14:09
I use vanilla slabs.

Log is on dropbox. 9MB
https://www.dropbox.com/s/92xlt5q1pay9sp9/latest.log?dl=1

**Comment by CJMinecraft01** [comment] 2020-06-14 13:28
Hmm. Can you also send a screenshot please? The console doesn't seem to show any errors related to my mod. Could you try to replicate this without Optifine installed as well please?

**Comment by agentwolf88** [comment] 2020-06-14 14:17
https://i.imgur.com/KtpgVfV.png
https://i.imgur.com/ICVvU3k.jpg

**Comment by CJMinecraft01** [comment] 2020-06-15 09:33
One thing which may fix this issue is to try and reload the textures. I cannot seem to recreate this myself

**Comment by agentwolf88** [comment] 2020-06-15 13:38
Optifine is the problem. When i use "internal shader" the slabs are invisible.

**Comment by tslindsay** [comment] 2020-06-17 07:22
I can confirm that this is also an issue with MC 1.15.2, mod version 2.5.1. When using OptiFine's "internal shader", vertical slabs are invisible on all or all-but-one face of the slab.

**Comment by ButterBuddy1213** [comment] 2020-06-18 00:09
I have only had this issue in 1.15.2. Vertical slabs only have texture on 1 side. Im running BSL shaders with optifine pre25

**Comment by CJMinecraft01** [comment] 2020-06-18 09:51
This seems to be an issue for all versions of the mod when Optifine is installed. I'm not 100% certain why this is happening cause I don't know what Optifine changes to improve FPS but I will try to take a look and see what I can do. It does seem that this occasionally happens with other mods too with Optifine but I will hopefully figure this out!

**Comment by CJMinecraft01** [comment] 2020-06-18 11:04
I've been doing some testing to try and identify the error and have noticed that the error doesn't occur on every block. Trying this with Improved Station's crafting slab seems fine for some reason.

**Comment by CJMinecraft01** [comment] 2020-06-18 12:21
In 1.15 this should now be fixed. I've slightly tweaked the rendering of vertical slabs but this may cause visual issues with ambient occlusion. Please let me know if this is fixed for you. I will begin downporting soon! Tested with preview_OptiFine_1.15.2_HD_U_G1_pre26.jar

**Comment by CJMinecraft01** [comment] 2020-06-18 14:09
This should be fixed in the latest versions!

**Closed as completed by CJMinecraft01** 2020-06-18 14:09 UTC
Labels: bug, 1.15.x, 1.14.x, 1.12.x
