### ISSUE TITLE
Player kick after placing slab on server.

### ISSUE THREAD

**Issue by KKotik** [CJMinecraft01/DoubleSlabs#156] opened 2020-11-25 14:03 UTC
[25Nov2020 16:56:43.393] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4448742f-512f-425c-a657-3dcbd1589ca2
[25Nov2020 16:56:43.394] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /25.49.152.178:52033
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at cjminecraft.doubleslabs.api.ServerWorldWrapper.func_201670_d(ServerWorldWrapper.java:227) ~[doubleslabs:3.4.10]
	at hellfirepvp.astralsorcery.common.constellation.SkyHandler.getContext(SkyHandler.java:96) ~[astralsorcery:1.16.4-1.13.1]
	at hellfirepvp.astralsorcery.common.util.ASMHookEndpoint.overrideSunBrightnessServer(ASMHookEndpoint.java:103) ~[astralsorcery:1.16.4-1.13.1]
	at net.minecraft.world.World.func_72966_v(World.java:688) ~[?:?]
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:188) ~[?:?]
	at cjminecraft.doubleslabs.api.ServerWorldWrapper.<init>(ServerWorldWrapper.java:75) ~[doubleslabs:3.4.10]
	at cjminecraft.doubleslabs.api.BlockInfo.setWorld(BlockInfo.java:107) ~[doubleslabs:3.4.10]
	at cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_226984_a_(SlabTileEntity.java:107) ~[doubleslabs:3.4.10]
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:408) ~[?:?]
	at net.minecraft.world.World.func_175690_a(World.java:640) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:391) ~[?:?]
	at net.minecraft.world.World.func_175625_s(World.java:598) ~[?:?]
	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.func_220053_a(VerticalSlabBlock.java:166) ~[doubleslabs:3.4.10]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215700_a(AbstractBlock.java:535) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196954_c(AbstractBlock.java:531) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_220071_b(AbstractBlock.java:277) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:543) ~[?:?]
	at net.minecraft.util.math.RayTraceContext$BlockMode.get(RayTraceContext.java:57) ~[?:?]
	at net.minecraft.util.math.RayTraceContext.func_222251_a(RayTraceContext.java:38) ~[?:?]
	at net.minecraft.world.IBlockReader.lambda$rayTraceBlocks$0(IBlockReader.java:50) ~[?:?]
	at net.minecraft.world.IBlockReader.func_217300_a(IBlockReader.java:142) ~[?:?]
	at net.minecraft.world.IBlockReader.func_217299_a(IBlockReader.java:45) ~[?:?]
	at se.mickelus.tetra.advancements.BlockLookTrigger.onPlayerTick(BlockLookTrigger.java:47) ~[tetra:3.3.1]
	at net.minecraftforge.eventbus.ASMEventHandler_433_BlockLookTrigger_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more
[25Nov2020 16:56:43.748] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: KKot1k lost connection: Internal server error
[25Nov2020 16:56:43.765] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: KKot1k left the game

**Comment by CJMinecraft01** [comment] 2021-06-18 16:39
Duplicate of #189

**Closed as completed by CJMinecraft01** 2021-06-18 16:39 UTC
