### ISSUE TITLE
Incompatible Slabs

### ISSUE THREAD

**Issue by Unicoranium** [CJMinecraft01/DoubleSlabs#20] opened 2020-03-24 21:01 UTC
Some modded slabs don't appear to work as expected.
Trying to place these slabs on top of a vanilla stone slab will instead place them in the block above as it would in vanilla. 

![image](https://user-images.githubusercontent.com/22139259/77476631-eaf53480-6de8-11ea-9e55-df3d2ceb7d94.png)

The slabs that aren't connected are from actually additions (left) and jaopca (right)

Looking at their source code, it appears they are implementing their slabs as normal blocks with custom logic instead of extending vanilla slabs. This may be the cause.

Possible solutions could be checking if the custom logic of a block matches that of a slab and treating it as such, or getting those mods to change their classes to actually implement slabs

[JAOPCA slab class](https://github.com/TheLMiffy1111/JAOPCAAdditions/blob/1.12/src/main/java/thelm/jaopca/additions/block/BlockSlabBase.java) (Not working)
[Applied Energistics slab class](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/decorative/slab/BlockSlabCommon.java) (Working)

Edit: Changed image to have brighter slabs from the same mods for easier identification

**Comment by CJMinecraft01** [comment] 2020-03-24 21:24
Yes, this is correct. They have implemented the slabs in a slightly different way than vanilla slabs but it would be possible I believe for me to make this work through making a change to the code I'm using. For which Minecraft version btw?

**Comment by Unicoranium** [comment] 2020-03-24 21:37
Currently running MC 1.12.2 with DoubleSlabs-1.12-0.1.4.jar

There's also another bug with these slabs, which will probably be fixed with this already, but I'll state it anyways just in case. If I place one of these slabs and use it to place a double slab above it, it creates a vanilla double slab

![image](https://user-images.githubusercontent.com/22139259/77479347-9bfdce00-6ded-11ea-90bd-689bb61b8063.png)

All blocks place from bottom to top, left is vanilla double slab, right is doubleslabs double slab

**Comment by CJMinecraft01** [comment] 2020-03-24 22:02
Thanks for this. I'll take a look and fix these as soon as possible

**Comment by CJMinecraft01** [comment] 2020-04-04 12:09
Okay so the first issue should now be fixed regarding JAOPCA slabs, they should now work with the mod as well as a bunch more other mods. Let me know if the other issue is still present. Thanks :)

**Comment by CJMinecraft01** [comment] 2020-04-04 12:10
It is available in the latest update (forgot to mention that)

**Comment by pimalel233** [comment] 2020-04-04 15:45
Hi, I will add some more mods that have slabs not working well still:
Plants, Engineer's Decor.
@CJMinecraft01 I noticed that when using Double Slabs, chunk update tick (seen as teal line in optifine's lagmeter) doubles/triples for me when making those slabs creating a noticeable short freeze. Is it possible to somehow optimize it?

**Comment by CJMinecraft01** [comment] 2020-04-04 16:54
Hi, thanks for the other mods which have slabs which don't work. Through looking at how those mods implement slabs, it is apparent that they implement their slabs in a means which cannot be detected by my mod. One way that this can be rectified is if the mod authors were to attach some extra code which adds integration directly with my mod. Regarding lag please use the #18 issue to post reports there. Would you be able to provide a list of mods (or which modpack) you are using the mod with. I have just done testing with SkyFactory 4 (which is fairly intensive on my PC) and have found no issues; however I have experienced some block placement lag before on an older version and would like to test this for a newer version myself. Thanks for the report!

**Comment by pimalel233** [comment] 2020-04-04 22:02
@CJMinecraft01 Yeah, it was Dynamic Surroundings. I posted mod list in that thread, so far only problems I noticed were those two mods I mentioned and DS. Do you plan any fix for DS compatability? Maybe also add whitelist to the config file where we could add custom slabs that does not work?

**Comment by CJMinecraft01** [comment] 2020-04-05 09:05
Yeah I do plan to fix compatibility with DS, have been trying to figure out how. The issue with adding a whitelist is that I need to know which half of the block is already present and be able to set which half to use which is easy for vanilla like slabs as I have access to the block state property but with other mods I don't which is where the issue is. I will try my best though!

**Comment by Unicoranium** [comment] 2020-04-10 07:32
I can confirm some slabs that were originally not working are now working. However some still do not work as they would be expected to.

Modded slab on top
![image](https://user-images.githubusercontent.com/22139259/78960204-f61bb600-7ab2-11ea-820d-ee8e1b8cb05a.png)
Modded slab on bottom
![image](https://user-images.githubusercontent.com/22139259/78966385-659aa100-7ac5-11ea-93b7-2376722f14f9.png)

Source mod from left to right:
JAOPCAx3, Atum 2, Blockcraftery, NetherEx.

NetherEx and Atum 2 slabs appear to behave as though DoubleSlabs doesn't detect they are slabs.

There are two issues with the Blockcraftery slab. The first being its main functionality of mimicking other blocks is tied to its NBT which is not carried over even when you place the Blockcraftery slab first. It's special right click function I suspect would be harder to carry over to double slabs than just maintaining the existing nbt of the slab. Their second issue is they are partially transparent and cause the other half of their slab to be invisible.

JAOPCA slabs have an interesting situation. They appear to work fine as a bottom half, but as the top half they render on the bottom. Even as a double slab, the hit box is a full block but the bottom half

![image](https://user-images.githubusercontent.com/22139259/78967087-12c1e900-7ac7-11ea-98f6-965d6b978964.png)

The bottom three are the bottom half of their column, the right three are the top half of their row. They all still form a full block hitbox but only render on the bottom half and the colors seem to merge.

**Comment by CJMinecraft01** [comment] 2020-04-10 08:00
Yes when testing with JAOPCA slabs I noticed that the top half of the slab renders as the bottom but with the hitbox of the top. Is this the same for you?

**Comment by Unicoranium** [comment] 2020-04-10 17:36
Yes, it does the same, which I thought was weird since The One Probe (and f3) says its still a JAOPCA block, but at the same time JAOPCA hasn't updated their slabs in a long time so nothing on their end should've changed

**Comment by CJMinecraft01** [comment] 2020-04-10 17:37
Do the slabs work fine without my mod?

**Comment by CJMinecraft01** [comment] 2020-04-10 17:37
I think they might have a model issue

**Comment by Unicoranium** [comment] 2020-04-10 17:44
Just loaded a pack with just the JAOPCA mods and it has the same top half issue, but only for single slabs, double slabs appear as full blocks as expected

**Comment by CJMinecraft01** [comment] 2020-04-11 11:24
Regarding the other mods that you were having compatibility issues, apparently Twilight Forest and Erebus slabs don't work. The only way I can see to fix this is for the mod authors of the other mods to add direct compatibility with my mod which shouldn't be too hard hopefully. I'm going to have a go at adding this to their mod and doing a PR

**Comment by CJMinecraft01** [comment] 2020-04-11 12:58
The compatibility with Erebus, NetherEx and Atum 2 has been added in the latest version. I do plan to work on adding better support for Blockcraftery at a later date but I will have to alter how the slab creation and rendering works

**Comment by pimalel233** [comment] 2020-04-15 11:26
@CJMinecraft01 there should be a PR now that could work for compatability with Engineer's Decor but might need some more testing. I have not forwarded the topic to the dev of Plants as I have found out he is not developing the mod anymore.

**Comment by CJMinecraft01** [comment] 2020-04-15 11:28
Fantastic, I'll add it as soon as possible!

**Comment by CJMinecraft01** [comment] 2020-06-15 09:31
From what I can see this issue has been fairly quiet, unless there are any other compatibility issues, I'm closing this now.

**Closed as completed by CJMinecraft01** 2020-06-15 09:31 UTC
Labels: bug, enhancement, 1.12.x
