### ISSUE TITLE
Possible Incompatibility with WorldEdit

### ISSUE THREAD

**Issue by AugustLandmesser8** [CJMinecraft01/DoubleSlabs#119] opened 2020-09-10 13:12 UTC
GreenTartan35 on CurseForge:
Vertical slabs, when being attempted to be rotated by the WorldEdit //rotate command, led the game to crash. 
Moreover, the unsuccessfully rotated vertical slabs' icons cannot be properly displayed by HUD as well. 
Caused highly likely by DoubleSlab's current **incompatibility with WorldEdit**. 

--------------------------------------------------------------------------------

Crash Report pasted below:
---- Minecraft Crash Report ----
// Sorry :(

Time: 2020-09-09 03:55:14 EDT
Description: Unexpected error

java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203)
    at java.util.Optional.<init>(Optional.java:96)
    at java.util.Optional.of(Optional.java:108)
    at cjminecraft.doubleslabs.blocks.BlockVerticalSlab.lambda$getHalfState$1(BlockVerticalSlab.java:91)
    at java.util.Optional.flatMap(Optional.java:241)
    at cjminecraft.doubleslabs.blocks.BlockVerticalSlab.getHalfState(BlockVerticalSlab.java:86)
    at cjminecraft.doubleslabs.blocks.BlockVerticalSlab.getPickBlock(BlockVerticalSlab.java:391)
    at jobicade.betterhud.element.BlockViewer.getDisplayStack(BlockViewer.java:167)
    at jobicade.betterhud.element.BlockViewer.shouldRender(BlockViewer.java:103)
    at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:260)
    at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:279)
    at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:140)
    at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:56)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_478_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:119)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1420)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['danpad3'/1998, l='MpServer', x=-140.69, y=5.07, z=535.46]]
  Chunk stats: MultiplayerChunkCache: 1089, 1089
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-281,4,458), Chunk: (at 7,0,10 in -18,28; contains blocks -288,0,448 to -273,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 3012243 game time, 3275773 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 16 total; [EntityPlayerSP['danpad3'/1998, l='MpServer', x=-140.69, y=5.07, z=535.46], EntityColoredItemFrame['Colored Item Frame'/2053, l='MpServer', x=-373.97, y=7.50, z=498.50], EntityColoredItemFrame['Colored Item Frame'/2054, l='MpServer', x=-372.50, y=15.94, z=463.50], EntityColoredItemFrame['Colored Item Frame'/2055, l='MpServer', x=-372.50, y=15.94, z=459.50], EntityColoredItemFrame['Colored Item Frame'/2056, l='MpServer', x=-372.50, y=23.94, z=459.50], EntityColoredItemFrame['Colored Item Frame'/2057, l='MpServer', x=-372.50, y=23.94, z=463.50], EntityColoredItemFrame['Colored Item Frame'/2058, l='MpServer', x=-374.97, y=7.50, z=472.50], EntityColoredItemFrame['Colored Item Frame'/2059, l='MpServer', x=-371.97, y=7.50, z=478.50], EntityColoredItemFrame['Colored Item Frame'/2060, l='MpServer', x=-372.50, y=15.94, z=467.50], EntityColoredItemFrame['Colored Item Frame'/2061, l='MpServer', x=-372.50, y=23.94, z=467.50], EntityColoredItemFrame['Colored Item Frame'/2062, l='MpServer', x=-371.97, y=7.50, z=489.50], EntityHorse['Adi'/1999, l='MpServer', x=-154.02, y=4.00, z=541.97], EntityColoredItemFrame['Colored Item Frame'/2063, l='MpServer', x=-371.97, y=7.50, z=488.50], EntityWolf['Maximilian'/2000, l='MpServer', x=-153.85, y=4.00, z=538.42], EntityColoredItemFrame['Colored Item Frame'/2064, l='MpServer', x=-373.50, y=8.94, z=447.50], EntityLeashKnot['entity.LeashKnot.name'/2006, l='MpServer', x=-154.50, y=4.50, z=539.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.13.6
  Java Version: 1.8.0_202, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1125737616 bytes (1073 MB) / 3131047936 bytes (2986 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 81 mods loaded, 81 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                     | Version                     | Source                                        | Signature                                |
       |:------ |:---------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft              | 1.12.2                      | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                    | 9.42                        | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                    | 8.0.99.99                   | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                  | 14.23.5.2854                | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy      | 1.0.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | opticmanager           | 1.0                         | minecraft.jar                                 | None                                     |
       | LCHIJA | smoothfontcore         | mc1.12.2-2.1.2              | minecraft.jar                                 | None                                     |
       | LCHIJA | passableleavescore     | 1.0.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | smoothfont             | mc1.12.2-2.1.2              | SmoothFont-mc1.12.2-2.1.2.jar                 | None                                     |
       | LCHIJA | additionalbanners      | 1.1.76                      | AdditionalBanners-1.12.2-1.1.76.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | ambientenvironment     | 1.0.1                       | AmbientEnvironment-1.0.2.jar                  | None                                     |
       | LCHIJA | opframe                | 1.4.0                       | OnlinePicFrame_v1.4.40_mc1.12.2.jar           | None                                     |
       | LCHIJA | creativecore           | 1.10.0                      | CreativeCore_v1.10.16_mc1.12.2.jar            | None                                     |
       | LCHIJA | ambientsounds          | 3.0                         | AmbientSounds_v3.0.14_mc1.12.2.jar            | None                                     |
       | LCHIJA | jei                    | 4.16.1.301                  | jei_1.12.2-4.16.1.301.jar                     | None                                     |
       | LCHIJA | quark                  | r1.6-179                    | Quark-r1.6-179.jar                            | None                                     |
       | LCHIJA | autoreglib             | 1.3-32                      | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCHIJA | backups                | 1.5.6                       | Backups-1.12.2-1.5.6.jar                      | None                                     |
       | LCHIJA | bannermod              | 1.1.0                       | bannermod-1.1.0.jar                           | None                                     |
       | LCHIJA | forgelin               | 1.8.4                       | Forgelin-1.8.4.jar                            | None                                     |
       | LCHIJA | betterfoliage          | 2.2.0                       | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
       | LCHIJA | betterhud              | 1.4.3                       | betterhud-1.12.2-1.4.3.jar                    | None                                     |
       | LCHIJA | betterplacement        | 1.0.0-1                     | BetterPlacement-1.0.0-1.jar                   | None                                     |
       | LCHIJA | blocklayering          | 1.12.2-1.0.3                | blocklayering-1.12.2-1.0.3.jar                | None                                     |
       | LCHIJA | clumps                 | 3.1.2                       | Clumps-3.1.2.jar                              | None                                     |
       | LCHIJA | codechickenlib         | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | custombackgrounds      | 1.0                         | CustomBackgrounds-MC1.12-1.1.1.jar            | None                                     |
       | LCHIJA | customcursormod        | 1.2.2                       | CustomCursorMod-1.2.2.jar                     | None                                     |
       | LCHIJA | csb                    | 1.4.5                       | CustomSelectionBox-1.12.2-1.4.6.jar           | None                                     |
       | LCHIJA | doubleslabs            | 0.10.0                      | DoubleSlabs-1.12-0.10.0.jar                   | None                                     |
       | LCHIJA | effortlessbuilding     | 1.12.2-2.16                 | effortlessbuilding-1.12.2-2.16.jar            | None                                     |
       | LCHIJA | fakename               | 1.2                         | Fakename MC1.12.2 v1.2.jar                    | None                                     |
       | LCHIJA | fantasticlib           | 1.12.2.036                  | FantasticLib-1.12.2.036.jar                   | None                                     |
       | LCHIJA | fastleafdecay          | v14                         | FastLeafDecay-v14.jar                         | None                                     |
       | LCHIJA | fenceoverhaul          | 1.3.4                       | FenceOverhaul-1.3.4.jar                       | None                                     |
       | LCHIJA | freecam                | 1.0                         | freecam_by_kapiteon.jar                       | None                                     |
       | LCHIJA | cfm                    | 6.3.1                       | furniture-6.3.1-1.12.2.jar                    | None                                     |
       | LCHIJA | futuremc               | 0.2.4                       | future-mc-1.12.2-0.2.4.0.jar                  | None                                     |
       | LCHIJA | grounditemhighlighting | 1.12.2.003                  | GroundItemHighlighting-1.12.2.003.jar         | None                                     |
       | LCHIJA | highlighter            | 1.0                         | Highlighter[1.0-1.12.2].jar                   | None                                     |
       | LCHIJA | continousmusic         | 1.0.0                       | infinitemusic-1.12.2-1.0.0.jar                | None                                     |
       | LCHIJA | inventoryspam          | 1.0.5                       | InventorySpam-1.12.2-1.0.5.jar                | None                                     |
       | LCHIJA | inventorytweaks        | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | itemzoom               | 1.11                        | itemzoom_1.12.2-1.11.jar                      | None                                     |
       | LCHIJA | journeymap             | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                   | None                                     |
       | LCHIJA | keywizard              | 1.12.2-1.7.3                | keywizard-1.12.2-1.7.3.jar                    | None                                     |
       | LCHIJA | kleeslabs              | 5.4.12                      | KleeSlabs_1.12.2-5.4.12.jar                   | None                                     |
       | LCHIJA | landlust               | 1.12.2-0.3.6                | landlust-1.12.2-0.3.6.jar                     | None                                     |
       | LCHIJA | lunatriuscore          | 1.2.0.42                    | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
       | LCHIJA | mcwbridges             | 1.0.4                       | mcw-bridges-1.0.4-mc1.12.2.jar                | None                                     |
       | LCHIJA | mcwdoors               | 1.0                         | mcw-doors-1.0.0-mc1.12.2.jar                  | None                                     |
       | LCHIJA | mcwfurnitures          | 1.0.1                       | mcw-furniture-1.0.1-mc1.12.2beta.jar          | None                                     |
       | LCHIJA | mcwroofs               | 1.0.2                       | mcw-roofs-1.0.2-mc1.12.2.jar                  | None                                     |
       | LCHIJA | mcwwindows             | 1.0                         | mcw-windows-1.0.0-mc1.12.2.jar                | None                                     |
       | LCHIJA | menumobs               | 1.21                        | MenuMobs-1.12.2-1.21.jar                      | None                                     |
       | LCHIJA | modnametooltip         | 1.10.1                      | modnametooltip_1.12.2-1.10.1.jar              | None                                     |
       | LCHIJA | mousetweaks            | 2.10                        | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
       | LCHIJA | uteamcore              | 2.2.5.147                   | u_team_core-1.12.2-2.2.5.147.jar              | None                                     |
       | LCHIJA | musicplayer            | 2.1.0.85                    | music_player-1.12.2-2.1.0.85.jar              | None                                     |
       | LCHIJA | norecipebook           | 1.2.1                       | noRecipeBook_v1.2.2formc1.12.2.jar            | None                                     |
       | LCHIJA | neid                   | 1.5.4.4                     | NotEnoughIDs-1.5.4.4.jar                      | None                                     |
       | LCHIJA | nei                    | 2.4.3                       | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | notenoughroofs         | 0.8.0.1                     | notenoughroofs-1.12.2-0.8.0.1.jar             | None                                     |
       | LCHIJA | placebo                | 1.6.0                       | Placebo-1.12.2-1.6.0.jar                      | None                                     |
       | LCHIJA | playerhighlighter      | 1.1.7                       | Player-Highlighter-1.12.2-1.1.7.jar           | None                                     |
       | LCHIJA | reborncore             | 3.19.4.529                  | RebornCore-1.12.2-3.19.4.529-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | redstoneflux           | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
       | LCHIJA | schematica             | 1.8.0.169                   | Schematica-1.12.2-1.8.0.169-universal.jar     | None                                     |
       | LCHIJA | signpost               | 1.08.3                      | signpost-1.12.2-1.08.3.jar                    | None                                     |
       | LCHIJA | simplylight            | 1.12.2-0.8.7                | simplylight-1.12.2-0.8.7.jar                  | None                                     |
       | LCHIJA | stepup                 | 1.0.2-mc1.10-1.12.2         | StepUp-1.0.2-mc1.10-1.12.jar                  | None                                     |
       | LCHIJA | sutils                 | 1.0                         | StructureUtils-1.1.0.4.jar                    | None                                     |
       | LCHIJA | toastcontrol           | 1.8.1                       | Toast Control-1.12.2-1.8.1.jar                | None                                     |
       | LCHIJA | vbe                    | GRADLE:VERSION-GRADLE:BUILD | Vanilla Builders Extension-1.12.2-1.0.9.jar   | None                                     |
       | LCHIJA | vanillafix             | 1.0.10-150                  | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCHIJA | waitingtime            | 1.0.1                       | WaitingTime-1.0.1.jar                         | None                                     |
       | LCHIJA | walljump               | 1.3.2                       | walljump-1.12.2-1.3.2.jar                     | None                                     |
       | LCHIJA | worldtooltips          | 1.3.0                       | World-Tooltips-1.12.2-1.3.0-111.jar           | None                                     |
       | LCHIJA | mineralogy             | 3.8.0                       | Mineralogy-1.12.2-3.8.0.53.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | structurize            | 1.12.2-0.10.277-RELEASE     | structurize-1.12.2-0.10.277-RELEASE.jar       | None                                     |
       | LCHIJA | passableleaves         | 2.0.0                       | PassableLeaves-1.12.2-2.0.0.jar               | None                                     |
  Loaded coremods (and transformers): CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
                                        
                                      StructureUtilsASM (StructureUtils-1.1.0.4.jar)
                                        me.modmuss50.structureutils.StructureTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      FutureMC (future-mc-1.12.2-0.2.4.0.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      WTPlugin (WaitingTime-1.0.1.jar)
                                        com.blamejared.waitingtime.core.WTClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
                                        teamrtg.passableleaves.asm.PassableLeavesTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      OpticPatchingLoader (OpticManager_v1.1.9_mc1.12.2.jar)
                                        com.creativemd.opticmanager.OpticTransformer
  GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.32' Renderer: 'Intel(R) Iris(TM) Plus Graphics 640'
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.19.4.529
              Runtime Debofucsation 1
              RenderEngine: 1
  Suspected Mods: DoubleSlabs (doubleslabs), Better HUD (betterhud)
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.2
  OpenGL: Intel(R) Iris(TM) Plus Graphics 640 GL version 2.1 INTEL-10.36.32, Intel Inc.
  GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
           Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Unity-1.6.5-1.12-YABBandaid.zip, Clear Glass Pack 1.11 or 1.12.zip, PRJE Atmosphere 1.12.zip, More Animation 1.11.x-1.12.x-rv1.1.zip, AudioCraftV1.5.zip, CreativeMusic.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by CJMinecraft01** [comment] 2020-09-17 09:01
Hi! Thanks for the bug report. From further investigation, it appears that this issue is a duplicate of #109 and #107 so please follow the issue there. Whilst the issue occurred under a different scenario, it crashes on the same function so will be fixed at the same time :)

**Closed as completed by CJMinecraft01** 2020-09-17 09:01 UTC
Labels: bug, duplicate, 1.12.x
