### ISSUE TITLE
Laggy frames on server

### ISSUE THREAD

**Issue by AznDanny** [CJMinecraft01/DoubleSlabs#157] opened 2020-11-28 08:19 UTC
Hello, I downloaded this mod on my server and all my friends have it downloaded. However, 1 specific person keeps dropping to 1 frames every couple seconds and my other friend keeps getting stuck at 0 frames, however I am perfectly fine. It might be because I am the host of the server, but are there any fixes to this?

**Comment by CJMinecraft01** [comment] 2020-12-24 22:35
Thank you for the report and sorry for the delayed response. Could you please ask the person who is dropping frames to show me their log file when this occurs to see if I can see where the issue is coming from

**Comment by Berenvonbaggins** [comment] 2021-05-14 23:38
I too have experienced this same issue. As soon as I open the vertical slabs inv tab, I'll just start arbitrarily and randomly dropping to 0 FPS momentarily. This also affects my whole PC, not just the game. Just having it open in the background causes the spikes.
I'm using the 1.16.5 version of the mod, along with Obfuscate, Crayfish Furniture Mod, Create, Vanilla Builders Extensions, and Worldedit. Which log file would you like me to enclose?

**Comment by CJMinecraft01** [comment] 2021-05-15 22:26
The debug.log should be sufficient. Could you try this with 3.5.0rc2 if you haven't already?

**Comment by CJMinecraft01** [comment] 2021-06-18 18:03
Hi there! I believe that this should be fixed in the latest version as I've added some more optimisations to improve both the rendering and the running of the server :)

**Closed as completed by CJMinecraft01** 2021-06-18 18:03 UTC
