### ISSUE TITLE
[1.12.2] place any slab and its highly unstable, multiple crashes spammed in folder

### ISSUE THREAD

**Issue by Landiie** [CJMinecraft01/DoubleSlabs#154] opened 2020-11-05 03:45 UTC
I placed down a slab vertically using shift+click, the first time it crashed immediately, here is the log for that: [first crash](https://pastebin.com/NW1XCDzv)

i loaded back up the pack again, and suffered the same problem, however, i had an issue with it spamming crashes when i got close (vanillafix would tell me a problem had occured, but no crash). but then i jumped on it and it gave me the same crash

this seems entirely unique to the new rewrite of the mod, i will be using an older version until this is stable, thank you for your hard work!

**Comment by Sixdd6** [comment] 2020-11-28 12:50
Just posting to say I had a similar crash when placing a normal slab vertically next to an identical vertical slab.
[crash-2020-11-28_06.46.11-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5610601/crash-2020-11-28_06.46.11-server.txt)

**Comment by TheidenHD** [comment] 2020-12-17 15:50
https://github.com/TheidenHD/DoubleSlabs/releases/tag/0.11.1

**Comment by CJMinecraft01** [comment] 2020-12-24 22:31
Thank you for the bug report and sorry for the delayed response. I believe this is a duplicate of #140 :)

**Closed as completed by CJMinecraft01** 2020-12-24 22:31 UTC
Labels: bug, duplicate, 1.12.x
