### ISSUE TITLE
Ticking Entity Crash after pushing Slab

### ISSUE THREAD

**Issue by NielsPilgaard** [CJMinecraft01/DoubleSlabs#42] opened 2020-05-03 18:35 UTC
Hello!

I received a report from a player that his game crashed while pushing a slab with a Piston. Stacktrace indicates DoubleSlabs and Engineer's Decor, so I thought I'd report it both places.

https://gist.github.com/NillerMedDild/e5f403bc3bc957fcfa2db93eb6a3ca67

- DoubleSlabs-1.15-2.2.6
- engineersdecor-1.15.2-1.0.20-b6

**Comment by stfwi** [comment] 2020-05-06 13:43
Hi CJ, related issue is https://github.com/stfwi/engineers-decor/issues/95, I'll check at the weekend if a redef of the slabs in 1.15/1.14 on my side will do the trick, otherwise we have to apply the PR #34 (for 1.12) also to 1.14/1.15. Cheers -

**Comment by CJMinecraft01** [comment] 2020-05-06 15:19
I've just realised what I've done, I might should be able to fix this. I've simply forgot to use the support code for the causes suffocation check. I'm not 100% certain but hopefully I can fix this as soon as possible. Thanks for the issue!

**Comment by CJMinecraft01** [comment] 2020-05-06 16:06
Should be fixed in the latest version!

**Closed as completed by CJMinecraft01** 2020-05-06 16:06 UTC
Labels: bug, 1.15.x, 1.14.x

**Comment by NielsPilgaard** [comment] 2020-05-06 17:48
Awesome, thanks!
