### ISSUE TITLE
1.15/1.14 SP Crash on map load.

### ISSUE THREAD

**Issue by BentoGambin** [CJMinecraft01/DoubleSlabs#47] opened 2020-06-05 19:26 UTC
The game crashes as soon as the map loads to 100% 
Mod Ver. DoubleSlabs-1.15-2.4.2
don't  know if it has anything to do with it, (judging by the report, probably not) but i'm am using optifine pre 18. 
`(
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 05/06/20 16:21
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{doubleslabs:double_slab}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at cjminecraft.doubleslabs.tileentitiy.TileEntityVerticalSlab.getCapability(TileEntityVerticalSlab.java:306) ~[?:2.4.2] {re:classloading}
	at terrails.xnetgases.Utils.getGasHandlerFor(Utils.java:50) ~[?:1.0.0] {re:classloading}
	at terrails.xnetgases.gas.GasConnectable.canConnect(GasConnectable.java:19) ~[?:1.0.0] {re:classloading}
	at mcjty.xnet.modules.cables.blocks.ConnectorBlock.isConnectable(ConnectorBlock.java:260) ~[?:1.15-2.1.4-beta] {re:classloading}
	at mcjty.xnet.logic.LogicTools.lambda$null$5(LogicTools.java:114) ~[?:1.15-2.1.4-beta] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241] {}
	at mcjty.xnet.modules.controller.blocks.TileEntityController.createNetworkChecker(TileEntityController.java:190) ~[?:1.15-2.1.4-beta] {re:classloading}
	at mcjty.lib.varia.Cached$CachedImplementation.get(Cached.java:37) ~[?:1.15-4.1.0-beta] {re:classloading}
	at mcjty.xnet.modules.controller.blocks.TileEntityController.checkNetwork(TileEntityController.java:235) ~[?:1.15-2.1.4-beta] {re:classloading}
	at mcjty.xnet.modules.controller.blocks.TileEntityController.func_73660_a(TileEntityController.java:289) ~[?:1.15-2.1.4-beta] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1907) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerWorld,pl:mixin:APP:lithium.mixins.json:fast_tick_scheduler.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93)
	at cjminecraft.doubleslabs.tileentitiy.TileEntityVerticalSlab.getCapability(TileEntityVerticalSlab.java:306)
	at terrails.xnetgases.Utils.getGasHandlerFor(Utils.java:50)
	at terrails.xnetgases.gas.GasConnectable.canConnect(GasConnectable.java:19)
	at mcjty.xnet.modules.cables.blocks.ConnectorBlock.isConnectable(ConnectorBlock.java:260)
	at mcjty.xnet.logic.LogicTools.lambda$null$5(LogicTools.java:114)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at mcjty.xnet.modules.controller.blocks.TileEntityController.createNetworkChecker(TileEntityController.java:190)
	at mcjty.lib.varia.Cached$CachedImplementation.get(Cached.java:37)
	at mcjty.xnet.modules.controller.blocks.TileEntityController.checkNetwork(TileEntityController.java:235)
	at mcjty.xnet.modules.controller.blocks.TileEntityController.func_73660_a(TileEntityController.java:289)

-- Block entity being ticked --
Details:
	Name: xnet:controller // mcjty.xnet.modules.controller.blocks.TileEntityController
	Block: Block{xnet:controller}[error=false,facing=south]
	Block location: World: (-3103,142,-6655), Chunk: (at 1,8,1 in -194,-416; contains blocks -3104,0,-6656 to -3089,255,-6641), Region: (-7,-13; contains chunks -224,-416 to -193,-385, blocks -3584,0,-6656 to -3073,255,-6145)
	Block: Block{xnet:controller}[error=false,facing=south]
	Block location: World: (-3103,142,-6655), Chunk: (at 1,8,1 in -194,-416; contains blocks -3104,0,-6656 to -3089,255,-6641), Region: (-7,-13; contains chunks -224,-416 to -193,-385, blocks -3584,0,-6656 to -3073,255,-6145)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:1907)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2635
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Survivor
	Level seed: -1605638996956670221
	Level generator: ID 09 - terraforged, ver 0. Features enabled: true
	Level generator options: {rivers:{value:{tertiaryRivers:{value:{fade:{value:0.75f},maxBankHeight:{value:4},minBankHeight:{value:0},bedDepth:{value:3},bankWidth:{value:10},bedWidth:{value:4}}},riverFrequency:{value:1.0f},secondaryRiver:{value:{fade:{value:0.75f},maxBankHeight:{value:6},minBankHeight:{value:1},bedDepth:{value:4},bankWidth:{value:15},bedWidth:{value:5}}},primaryRivers:{value:{fade:{value:0.75f},maxBankHeight:{value:8},minBankHeight:{value:2},bedDepth:{value:5},bankWidth:{value:25},bedWidth:{value:8}}}}},features:{value:{vanillaWaterFeatures:{value:"false"},strataDecorator:{value:"true"},naturalSnowDecorator:{value:"true"},smoothLayerDecorator:{value:"true"},erosionDecorator:{value:"true"},customBiomeFeatures:{value:"true"}}},structures:{value:{villageDistance:{value:2},strongholdSpread:{value:3},oceanMonumentSeparation:{value:3},biomeStructureDistance:{value:4},mansionDistance:{value:3},oceanMonumentSpacing:{value:3},strongholdDistance:{value:3}}},generator:{value:{world:{value:{seaLevel:{value:63},worldHeight:{value:256},oceanSize:{value:0.25f}}},biome:{value:{biomeWarpStrength:{value:70},biomeSize:{value:200},biomeWarpScale:{value:35}}},land:{value:{mountainScale:{value:950},continentScale:{value:4000},regionSize:{value:1000}}},biomeEdgeNoise:{value:{octaves:{value:2},strength:{value:24},scale:{value:8},type:{value:"PERLIN"},lacunarity:{value:2.5f},gain:{value:0.5f}}}}},climate:{value:{temperature:{value:{min:{value:0.0f},max:{value:1.0f}}},moisture:{value:{min:{value:0.0f},max:{value:1.0f}}}}},filters:{value:{erosion:{value:{erosionRate:{value:0.5f},depositeRate:{value:0.2f},iterations:{value:12000}}},smoothing:{value:{smoothingRadius:{value:1.75f},smoothingRate:{value:0.85f},iterations:{value:1}}}}},version:{value:1},terrain:{value:{badlands:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:2.0f}}},mountains:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:0.5f}}},globalVerticalScale:{value:0.985f},dales:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:2.0f}}},globalHorizontalScale:{value:1.0f},plains:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:5.0f}}},hills:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:2.0f}}},plateau:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:2.0f}}},torridonian:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:0.5f}}},volcano:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:1.0f}}},steppe:{value:{baseScale:{value:1.0f},verticalScale:{value:1.0f},horizontalScale:{value:1.0f},weight:{value:5.0f}}}}},dimensions:{value:{baseLayer:{value:{minDepth:{value:1},material:{value:"minecraft:bedrock"},variance:{value:4}}},dimensionGenerators:{value:{nether:{value:"default"},end:{value:"default"}}}}}}
	Level spawn location: World: (-2981,122,-6769), Chunk: (at 11,7,15 in -187,-424; contains blocks -2992,0,-6784 to -2977,255,-6769), Region: (-6,-14; contains chunks -192,-448 to -161,-417, blocks -3072,0,-7168 to -2561,255,-6657)
	Level time: 3844323 game time, 613726 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 45510 (now: false), thunder time: 121206 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2180773912 bytes (2079 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.89.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.89.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.89.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.89.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre19.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.89.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.89
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 DONE}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		inventoryprofiles-forge-1.15.2-0.2.1.jar Inventory Profiles {inventoryprofiles@0.2.1 DONE}
		upsizer-mc1.15.2-5.1.jar Upsizer {upsizer@5.1.0 DONE}
		oreveins-forge-1.15.2-5.1.3.jar Realistic Ore Veins {oreveins@5.1.3 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		Controlling-6.1.3.jar Controlling {controlling@6.1.3 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		NamePain-1.15.2-Forge-1.2.2.jar Name Pain {namepain@1.2.2 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		DarkUtilities-1.15.2-3.0.5.jar Dark Utilities {darkutils@3.0.5 DONE}
		Apotheosis-1.15.2-3.1.0.jar Apotheosis {apotheosis@3.1.0 DONE}
		magicaljewelry-1.15.2_1.0.1b.jar Magical Jewelry {magicaljewelry@1.15.2_1.0.0b DONE}
		PickUpNotifier-v1.1.2-1.15.2.jar Pick Up Notifier {pickupnotifier@1.1.2 DONE}
		MekanismGenerators-1.15.2-9.10.7.420.jar Mekanism: Generators {mekanismgenerators@9.10.7 DONE}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		XNetGases-1.15.2-1.0.0.jar XNet Gases {xnetgases@1.0.0 DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		corpse-1.15.2-1.0.4.jar Corpse {corpse@1.15.2-1.0.3 DONE}
		industrial-foregoing-1.15.2-2.3.2-e3bf186.jar Industrial Foregoing {industrialforegoing@2.3.2 DONE}
		repurposedstructures-1.15.2-1.4.4.jar Repurposed Structures {repurposed_structures@1.15.2-1.4.4 DONE}
		chunkt-1.15.2-1.0.3.jar Chunkt {chunkt@1.15.2-1.0.3 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		MekanismTools-1.15.2-9.10.7.420.jar Mekanism: Tools {mekanismtools@9.10.7 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		Better+Muffling-1.15.2-0.5.0-Beta.jar Better Muffling {bettermuffling@0.5.0-Beta DONE}
		ScalingHealth-1.15.2-3.0.7+54.jar Scaling Health {scalinghealth@3.0.7+54 DONE}
		CodeChickenLib-1.15.2-3.3.0.373-universal.jar CodeChicken Lib {codechickenlib@3.3.0.373 DONE}
		leavesdecayonotherleaves-1.1.jar Leaves Decay on other Leaves {leavesdecayonotherleaves@1.1 DONE}
		Cyclic-1.15.2-0.4.1.jar Cyclic {cyclic@1.15.2-0.4.1 DONE}
		cullparticles-1.0.jar Cull Particles {cullparticles@1.0 DONE}
		SaveMyStronghold-1.15.2-1.0.0.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.0 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		simplefriedegg-v0.2.jar Simple Fried Egg {simplefriedegg@1.0.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		caelus-FORGE-1.15.2-2.0-beta2.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta2 DONE}
		vmt-1.15.2-1.2.jar Villager Memory Tweaks {vmt@1.15.2-1.0 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		BotanyPots-1.15.2-2.0.14.jar BotanyPots {botanypots@2.0.14 DONE}
		autoattack-1.0.jar Example Mod {autoattack@1.0 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.0-beta.jar McJtyLib {mcjtylib@1.15-4.1.0-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.4-beta.jar XNet {xnet@1.15-2.1.4-beta DONE}
		rftoolsstorage-1.15-1.1.3-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.3-beta DONE}
		rftoolscontrol-1.15-3.0.1-beta.jar RFToolsControl {rftoolscontrol@1.15-3.0.1-beta DONE}
		no-potion-offset-1.0.0.jar No Potion Offset {no-potion-offset-forge@1.0.0 DONE}
		enchantability-6.1.jar Enchantability {enchantability@6.1 DONE}
		EnderStorage-1.15.2-2.5.0.142-universal.jar EnderStorage {enderstorage@2.5.0.142 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.89-universal.jar Forge {forge@31.1.89 DONE}
		DramaticDoors-1.15.2-1.0.1.jar Dramatic Doors {dramaticdoors@1.15.2-1.0.1 DONE}
		QuickLeafDecay-MC1.15.2-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		ultra_amplified_dimension-1.15.2-7.4.2.jar Ultra Amplified Dimension {ultra_amplified_dimension@1.15.2-7.4.2 DONE}
		ColossalChests-1.15.2-1.7.6.jar ColossalChests {colossalchests@1.7.6 DONE}
		forge-1.15.2-31.1.89-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		titanium-1.15.2-2.4.0.jar Titanium {titanium@2.4.0 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		packedup-1.0.8-mc1.15.jar PackedUp {packedup@1.0.8 DONE}
		towers_of_the_wild-1.15.2-1.1.0.jar Towers Of the Wild {towers_of_the_wild@1.15.2-1.1.0 DONE}
		Ding-1.15.2-1.1.0.jar Ding {ding@1.1.0 DONE}
		JAHM+v1.2+[1.15.2].jar Just Another Head Mod {justanotherheadmod@1.2 DONE}
		rftoolsbuilder-1.15-2.1.2-beta.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.2-beta DONE}
		jeiintegration_1.15.2-3.1.0.jar JEI Integration {jeiintegration@3.1.0 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-240.jar Quark {quark@r2.1-240 DONE}
		Charm-1.15.2-1.5.7.jar Charm {charm@1.15.2-1.5.7 DONE}
		Strange-1.15.2-1.0.0-beta.3.jar Strange {strange@1.15.2-1.0.0-beta.3 DONE}
		smooth-scrolling-everywhere-1.2.jar Smooth Scrolling Everywhere {smooth-scrolling-everywhere@1.2 DONE}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 DONE}
		performant-1.15-2.11m.jar Performant {performant@2.11m DONE}
		DoubleSlabs-1.15-2.4.2.jar Double Slabs {doubleslabs@2.4.2 DONE}
		SlimeTweaks-1.15.2-1.0.2.jar SlimeTweaks {slimetweaks@1.0.2 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
	Player Count: 0 / 8; []
	Data Packs: mod:oreveins (incompatible), mod:magicaljewelry, mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:towers_of_the_wild, mod:bettercaves (incompatible), mod:xnetgases, mod:ultra_amplified_dimension (incompatible), mod:justanotherheadmod, mod:jeiintegration (incompatible), mod:rftoolsutility (incompatible), mod:extlights, mod:dramaticdoors (incompatible), mod:rftoolscontrol (incompatible), mod:bettermuffling (incompatible), mod:pickupnotifier, mod:jeresources (incompatible), mod:upsizer, mod:appleskin (incompatible), mod:slimetweaks (incompatible), mod:overloadedarmorbar (incompatible), vanilla, mod:aiimprovements (incompatible), mod:apotheosis (incompatible), mod:attributefix (incompatible), mod:autoattack (incompatible), mod:autoreglib (incompatible), mod:blur (incompatible), mod:bookshelf (incompatible), mod:charm (incompatible), mod:chunkt (incompatible), mod:clumps (incompatible), mod:cofh_core (incompatible), mod:colossalchests (incompatible), mod:controlling (incompatible), mod:corpse, mod:cullparticles (incompatible), mod:curios (incompatible), mod:cyclic (incompatible), mod:cyclopscore (incompatible), mod:damage_indicator (incompatible), mod:darkutils (incompatible), mod:doubleslabs, mod:dungeoncrawl (incompatible), mod:enchantability (incompatible), mod:enchdesc (incompatible), mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fluxnetworks, mod:forge (incompatible), mod:fpsreducer, mod:industrialforegoing (incompatible), mod:inventoryprofiles (incompatible), mod:jei (incompatible), mod:journeymap (incompatible), mod:leavesdecayonotherleaves, mod:lithium, mod:mcjtylib (incompatible), mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:namepain, mod:netherportalfix (incompatible), mod:no-potion-offset-forge (incompatible), mod:performant (incompatible), mod:phosphor, mod:placebo (incompatible), mod:quark, mod:quickleafdecay, mod:randompatches (incompatible), mod:rangedpumps (incompatible), mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:repurposed_structures, mod:rftoolsbase (incompatible), mod:rftoolsbuilder (incompatible), mod:rftoolspower (incompatible), mod:rftoolsstorage (incompatible), mod:savemystronghold (incompatible), mod:scalinghealth, mod:silentlib (incompatible), mod:smooth-scrolling-everywhere (incompatible), mod:strange (incompatible), mod:swingthroughgrass (incompatible), mod:terraforged, mod:theoneprobe (incompatible), mod:titanium (incompatible), mod:valhelsia_structures (incompatible), mod:vmt (incompatible), mod:xnet (incompatible), mod:mousetweaks (incompatible), mod:extradisks, mod:naturescompass (incompatible), mod:packedup, mod:toolbelt (incompatible), mod:trashslot (incompatible), mod:bonsaitrees2, mod:libnonymous (incompatible), file/bentostweaks, mod:botanypots (incompatible), mod:ding (incompatible), mod:simplefriedegg, mod:caelus (incompatible), mod:curiouselytra (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre19
	OptiFine Build: 20200601-002451
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.05p2
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4)
`

**Comment by BentoGambin** [comment] 2020-06-05 21:27
My guess is that it happens because I updated a few versions of DS without booting the map.

**Comment by CJMinecraft01** [comment] 2020-06-05 21:31
The issue is not related to anything that you have done. I've made a mistake on my part due to when other mods are trying to interact with a double slab. To reuse code I'm using some of the vertical slab code, however I forgot to tweak how it works with capabilities. I should be able to get a fix out for tomorrow. Sorry for the delay (I've been working solid on this for a week)

**Comment by CJMinecraft01** [comment] 2020-06-06 11:37
This should be fixed in the latest version!

**Closed as completed by CJMinecraft01** 2020-06-06 11:37 UTC
Labels: bug, 1.15.x, 1.14.x

**Comment by BentoGambin** [comment] 2020-06-06 21:46
Great!
