### ISSUE TITLE
1.14 cannot place double slabs below y 32

### ISSUE THREAD

**Issue by torterra2234** [CJMinecraft01/DoubleSlabs#37] opened 2020-04-17 19:14 UTC
Slabs work fine at and above y32, y31 and below however dont seem to work

image below of this in an otherwise vanilla install, so does not seemm to be mod compat based (previously observed with create slabs)

![image](https://user-images.githubusercontent.com/6496072/79605264-7cee1580-80e7-11ea-81d3-d24cf38f7687.png)

**Comment by CJMinecraft01** [comment] 2020-04-20 11:04
This is certainly not a bug I was expecting to find but I think I may have found where the issue is coming from and will fix this in the next version which I'm working on atm

**Comment by CJMinecraft01** [comment] 2020-04-20 11:53
Fixed in the latest version!

**Closed as completed by CJMinecraft01** 2020-04-20 11:53 UTC
Labels: bug, 1.14.x
